### ISSUE TITLE
wrong query from power-scheduler

### ISSUE THREAD

**Issue by choonho** [spaceone-dev/inventory#140]
~~~
2021-02-24T22:29:59.792Z [INFO] tnx-4d44d3708e0b Server.list (service.py:73) (REQEUST) => {"query": {"filter": [{"k": "resource_group_id", "v": "rsc-grp-3f796cc5f658", "o": "eq"}], "only": ["reference.resource_id", "cloud_service_group", "cloud_service_type", "collection_info.secrets", "region_code", "provider", "data.power_state", "cloud_service_id"]}, "domain_id": "domain-58010aa2e451"}
2021-02-24T22:29:59.814Z [ERROR] tnx-4d44d3708e0b Server.list (service.py:144) (Error) => Database query failed. (reason = Cannot resolve field "cloud_service_id")
	error_code = ERROR_DB_QUERY
	status_code = INTERNAL
	message = Database query failed. (reason = Cannot resolve field "cloud_service_id")  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/model/mongo_model/__init__.py", line 447, in query
    vos = vos.only(*only)
  File "/usr/local/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1006, in only
    return self.fields(True, **fields)
  File "/usr/local/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1077, in fields
    fields = queryset._fields_to_dbfields(fields)
  File "/usr/local/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1852, in _fields_to_dbfields
    raise err
  File "/usr/local/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1831, in _fields_to_dbfields
    for f in self._document._lookup_field(field_parts)
  File "/usr/local/lib/python3.8/site-packages/mongoengine/base/document.py", line 1100, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "cloud_service_id"
~~~

**Comment by choonho** [comment]
Wrong data of google controller

~~~
 controller-503824047e7e | google_cloud_power_controller | google_cloud | {'supported_schema': ['google_oauth_client_id']}            | {'plugin_id': 'plugin-3a774165692b', 'version': '1.1', 'options': {}, 'provider': 'google_cloud', 'metadata': {'supported_resource_type': ['inventory.Server?provider=google_cloud&cloud_service_group=ComputeEngine&cloud_service_type=Instance', 'inventory.CloudService?provider=google_cloud&cloud_service_type=ComputeEngine&cloud_service_type=InstanceGroup', 'inventory.CloudService?provider=google_cloud&cloud_service_type=CloudSQL&cloud_service_type=Instance'], 'reference_keys': [{'required_keys': ['reference.resource_id', 'cloud_service_group', 'cloud_service_type', 'collection_info.secrets', 'region_code', 'provider', 'data.power_state'], 'resource_type': 'inventory.Server?provider=google_cloud&cloud_service_group=ComputeEngine&cloud_service_type=Instance'}, {'required_keys': ['reference.resource_id', 'cloud_service_group', 'cloud_service_type', 'collection_info.secrets', 'region_code', 'provider', 'data.power_scheduler'], 'resource_type': 'inventory.CloudService?provider=google_cloud&cloud_service_type=ComputeEngine&cloud_service_type=InstanceGroup'}, {'required_keys': ['reference.resource_id', 'cloud_service_group', 'cloud_service_type', 'collection_info.secrets', 'region_code', 'provider'], 'resource_type': 'inventory.CloudService?provider=google_cloud&cloud_service_type=CloudSQL&cloud_service_type=Instance'}], 'filter_format': []}} | 2021-02-02T14:55:55.474Z | domain-58010aa2e451
~~~
